version: '3.9'

services:
  openbanking-api:
    image: openbanking-api
    container_name: openbanking-api
    build:
      context: ../openbanking-api
    env_file:
      - .env
    ports:
      - "6800:6800"
    working_dir: /app
    networks:
      - openbanking-network

  js-rendering-service:
    container_name: js-rendering-service
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    networks:
      - openbanking-network

networks:
  openbanking-network:
    driver: bridge