version: '3.9'

services:
  openbanking-api:
    image: openbanking-api
    container_name: openbanking-api
    build:
      context: ../openbanking-api
    env_file:
      - .env
    ports:
      - 6800:6800
    volumes:
      - ../openbanking-api:/app
    working_dir: /app
    networks:
      - openbanking-network

networks:
  openbanking-network:
    driver: bridge